# cargo deny check: known vulnerabilities, licences that can go into a GPL-3.0-or-later
# program, and crates only from crates.io.

[graph]
targets = ["x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu"]

[advisories]
unmaintained = "workspace"

[licenses]
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "GPL-3.0-or-later",
    "MIT",
    "Unicode-3.0",
    "Unlicense",
]

[bans]
multiple-versions = "allow"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
